configs:
  ts-serve-homebridge:
    content: |
      {"TCP":{"443":{"HTTPS":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:8581"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

  dnsmasq-filtered-aaaa-conf:
    content: |
      no-resolv
      server=1.1.1.1
      server=8.8.8.8
      cache-size=10000
      # log-queries
      # log-facility=-
      filter-AAAA
      filter-rr=AAAA


services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    volumes:
      - "homebridge:/homebridge"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: "${NODE_NAME}"
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    devices:
      - "/dev/net/tun:/dev/net/tun"
    env_file: .env
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=/config/serve.json
    volumes:
      - "ts-data:/var/lib/tailscale"
    configs:
      - source: ts-serve-homebridge
        target: /config/serve.json
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  xray:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - "./xray-config.json:/usr/local/etc/xray/config.json:ro"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  dnsmasq-filtered-aaaa:
    image: dockurr/dnsmasq:2
    container_name: dnsmasq-filtered-aaaa
    restart: unless-stopped
    expose:
      - "53/udp"
      - "53/tcp"
    configs:
      - source: dnsmasq-filtered-aaaa-conf
        target: /etc/dnsmasq.conf
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  dnsmasq:
    image: dockurr/dnsmasq:2
    container_name: dnsmasq
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - "./dnsmasq.conf:/etc/dnsmasq.conf:ro"
    ports:
      - "${SERVER_LAN_IP}:53:53/tcp"
      - "${SERVER_LAN_IP}:53:53/udp"
      - "[${SERVER_LAN_IPV6}]:53:53/tcp"
      - "[${SERVER_LAN_IPV6}]:53:53/udp"
    command: >
      --no-resolv
      --server=1.1.1.1
      --server=8.8.8.8
      --cache-size=10000
      --listen-address=${SERVER_LAN_IP}
      --listen-address=${SERVER_LAN_IPV6}
      --except-interface=lo
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

volumes:
  ts-data:
  homebridge:
