configs:
  ts-serve-homebridge:
    content: |
      {"TCP":{"443":{"HTTPS":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:8581"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:
  homebridge:
    image: ghcr.io/homebridge/homebridge:latest
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    volumes:
      - "homebridge:/homebridge"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: "${NODE_NAME}"
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    devices:
      - "/dev/net/tun:/dev/net/tun"
    env_file: .env
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=/config/serve.json
    volumes:
      - "ts-data:/var/lib/tailscale"
    configs:
      - source: ts-serve-homebridge
        target: /config/serve.json
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  unifi-network:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - MEM_LIMIT=default
      - MEM_STARTUP=default
      - MONGO_USER=unifi
      - MONGO_PASS=${MONGO_USER_PASS}
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    volumes:
      - unifi-network-data:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    depends_on:
      - unifi-db
    profiles: ["unifi"]

  unifi-db:
    image: docker.io/mongo:4.4.18
    container_name: unifi-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
      - MONGO_USER=unifi
      - MONGO_PASS=${MONGO_USER_PASS}
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    expose:
      - 27017
    volumes:
      - "unifi-db:/data/db"
      - "./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    profiles: ["unifi"]

volumes:
  ts-data:
  homebridge:
  unifi-network-data:
  unifi-db:
