services:
  mtproto:
    image: telegrammessenger/proxy:latest
    container_name: mtproto
    restart: unless-stopped
    volumes:
      - "mtproto:/data"
    env_file: .env
    ports:
      - "$MTPROTO_PORT:443"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  xray:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray
    restart: unless-stopped
    volumes:
      - "./xray-config.json:/usr/local/etc/xray/config.json:ro"
    env_file: .env
    ports:
      - "$SERVER_IP:$VLESS_PORT:10237/tcp"
    expose:
      - "$VLESS_PORT"
    networks:
      xraynet:
        ipv4_address: 172.20.0.10
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

volumes:
  mtproto:

networks:
  xraynet:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
